### ISSUE TITLE
Add `sql.Scanner` to the interface whitelist for `sqlx`

### ISSUE THREAD

**Issue by tmzane** [go-simpler/musttag#103]

**Comment by ccoVeille** [comment]
While the PR and issue are clear what you do, I'm unsure why you did it.

I assume it was a false positive or something, but explaining in this issue why you made the change would be interesting

Thanks

**Comment by tmzane** [comment]
@ccoVeille Hello,

Types that implement `sql.Scanner` know how to unmarshal themselves, `sqlx` will call the corresponding method, if it exists. My use case was a json field in the struct, which was passed to `sqlx` functions. The database contains json values for the corresponding column, so there was no need for the `db` tag.

**Comment by tmzane** [comment]
Something like:

```
type Foo struct {
    Bar string `db:"bar"`
    Baz struct {
    // json fields here w/o the `db` tag.
    } `db:"baz"`
}
```

where `Baz` implements `sql.Scanner`.

**Comment by tmzane** [comment]
I agree, interface whitelists for the builtin packages are worth a mention in the README. I'll update the docs later

**Comment by ccoVeille** [comment]
> I agree, interface whitelists for the builtin packages are worth a mention in the README. I'll update the docs later

I created #105

**Comment by tmzane** [comment]
Thank you!
